name: Candlestick Backend Pipeline

on: push

jobs:
    unit_test_job:
        name: Unit Test
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            #- name: Setup Python
            #  uses: actions/setup-python@v5
            #  with:
            #    python-version: '3.13'

            - name: Cache Python dependencies
              uses: actions/cache@v4
              id: pip-cache
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            - name: Install Dependencies
              if: steps.pip-cache.outputs.cache-hit != 'true' 
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  pip install pytest coverage pytest-cov --break-system-packages
                  pip install -r requirements.txt --break-system-packages
              
            - name: Unit Test
              run: pytest --junitxml=artifacts/event-test.xml

            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Event Test Result
                path: artifacts/event-test.xml
                retention-days: 5
    code_coverage_job:
        name: Code Coverage
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            #- name: Setup Python
            #  uses: actions/setup-python@v5
            #  with:
            #    python-version: '3.13'

            - name: Cache Python dependencies
              uses: actions/cache@v4
              id: pip-cache
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            - name: Install Dependencies
              if: steps.pip-cache.outputs.cache-hit != 'true' 
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  pip install pytest coverage pytest-cov --break-system-packages
                  pip install -r requirements.txt --break-system-packages

            - name: Run Coverage
              run: |
                  pytest --cov --cov-report=xml:covarage
                  pytest --cov --cov-report=html:coverage
                  #python3 -m coverage report > coverage/coverage_report.txt
                  #python3 -m coverage xml > coverage/coverage_report.xml
            - name: Archive Code Coverage Results
              uses: actions/upload-artifact@v4
              with:
                name: Code Coverage Result
                path: coverage
                retention-days: 5
    verify_unit_test_job:
        name: Verify Unit Test
        needs: unit_test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Download Test Results
              uses: actions/download-artifact@v4
              with:
                name: Event Test Result

            - name: Simple Display Results
              run: |
                  cat event-test.xml
    build_image_job:
        name: Docker Containerization
        needs: unit_test_job
        if: github.ref == 'refs/head/main'
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Docker Build
              run: sudo docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest .

            - name: Docker Login
              run: sudo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD}}

            - name: Docker Publish
              run: sudo docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Docker Logout
              run: sudo docker logout https://docker.io
    test_image_job:
        name: Test Docker Image
        if: github.ref == 'refs/head/main'
        needs: build_image_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Run Rabbit MQ
              run: |
                  sudo docker run -itd -p 15672:15672 -p 5672:5672 --network=shadow-net --name rabbitmq rabbitmq:3-management
                  sleep 30s
              
            - name: Run Python Backend
              run: |
                  sudo docker run -itd --link rabbitmq:rabbitmq --network=shadow-net --name market-app ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
                  sleep 30s

            - name: Test Docker Image
              run: |
                  sudo docker exec -i market-app cat /app/test.log

            - name: Clean Docker Deployments
              run: |
                  sudo docker stop market-app && sudo docker rm market-app
                  sudo docker stop rabbitmq && sudo docker rm rabbitmq
    deploy_image_job:
        name: Deploy Docker Image
        if: github.ref == 'refs/head/main'
        needs: test_image_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Deploy Application
              run: |
                  cat README.md
