name: Candlestick Backend Pipeline

on: push

jobs:
    unit_test_job:
        name: Unit Test
        #if: github.ref == 'refs/head/feature'
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            #- name: Setup Python
            #  uses: actions/setup-python@v5
            #  with:
            #    python-version: '3.13'

            - name: Cache Python dependencies
              uses: actions/cache@v4
              id: pip-cache
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            - name: Install Dependencies
              if: steps.pip-cache.outputs.cache-hit != 'true' 
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  pip install pytest coverage pytest-cov --break-system-packages
                  pip install -r requirements.txt --break-system-packages
              
            - name: Unit Test
              run: pytest --junitxml=artifacts/event-test.xml

            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Event Test Result
                path: artifacts/event-test.xml
                retention-days: 5
    code_coverage_job:
        name: Code Coverage
        if: github.ref == 'refs/head/feature'
        needs: unit_test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            #- name: Setup Python
            #  uses: actions/setup-python@v5
            #  with:
            #    python-version: '3.13'

            - name: Cache Python dependencies
              uses: actions/cache@v4
              id: pip-cache
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            - name: Install Dependencies
              if: steps.pip-cache.outputs.cache-hit != 'true' 
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  pip install pytest coverage pytest-cov --break-system-packages
                  pip install -r requirements.txt --break-system-packages

            - name: Run Coverage
              run: |
                  pytest --cov --cov-report=xml:covarage
                  pytest --cov --cov-report=html:coverage
                  #python3 -m coverage report > coverage/coverage_report.txt
                  #python3 -m coverage xml > coverage/coverage_report.xml
            - name: Archive Code Coverage Results
              uses: actions/upload-artifact@v4
              with:
                name: Code Coverage Result
                path: coverage
                retention-days: 5
    verify_unit_test_job:
        name: Verify Unit Test
        if: github.ref == 'refs/head/feature'
        needs: unit_test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Download Test Results
              uses: actions/download-artifact@v4
              with:
                name: Event Test Result

            - name: Simple Display Results
              run: |
                  cat event-test.xml
    build_image_job:
        name: Docker Containerization
        needs: unit_test_job
        #if: github.ref == 'refs/head/main'
        runs-on: self-hosted
        steps:
            - name: Docker Login
              uses: docker/login-action@v2.2.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Docker Build
              uses: docker/build-push-action@v4
              with:
                context: .
                push: false
                tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Docker Image Testing
              run: |
                  docker run --name rabbitmq -itd \
                      -p 15672:15672 \
                      -p 5672:5672 \
                      rabbitmq:3-management
                  sleep 60s
                  docker run --name backend-app -itd \
                      --env=RABBITMQ=rabbitmq \
                      --env=JAVA_API=java-api \
                      --link rabbitmq:rabbitmq \
                      ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
                  sleep 60s
                  docker exec -i backend-app cat /app/test.log
                  docker stop rabbitmq && docker rm rabbitmq
                  docker stop backend-app && docker rm backend-app

            - name: Docker Push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            #- name: Docker Logout
            #  run: sudo docker logout https://docker.io
    deploy_image_job:
        name: Deploy Docker Image
        #if: github.ref == 'refs/head/main'
        needs: build_image_job
        outputs:
          APP_INGRESS_URL: ${{ steps.set-ingress-host-id.outputs.APP_INGRESS_HOST}}
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Install Kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.33.6'

            - name: Set Kubeconfig
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}
                
            - name: Fetch Kubernetes CLuster Details
              run: |
                  kubectl version
                  echo ............................
                  kubectl get nodes

            - name: Replace Token in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS}}
                IMAGE: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Check Files
              run: |
                  cat kubernetes/development/*.yaml

            - name: Deploy to Dev Env
              run: |
                  kubectl apply -f kubernetes/development

            - name: Set App Ingress Host URL
              id: set-ingress-host-id
              run: |
                  echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o json | jq -r '.items[] | .spec.rules[] | .host')" >> "$GITHUB_OUTPUT"
                  #echo $APP_INGRESS_HOST
    integration_test_job:
        name: Dev Integration Testing
        #if: github.ref == 'refs/head/main'
        needs: deploy_image_job
        runs-on: self-hosted
        steps:
            - name: Test URL Output using cURL
              env:
                URL: ${{ needs.deploy_image_job.outputs.APP_INGRESS_URL }}
              run: |
                  echo $URL
                  echo "................................"
                  curl http://$URL