name: Candlestick Backend Pipeline

on: push

jobs:
    build_job:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Docker Build
              run: sudo docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest .

            - name: Docker Login
              run: sudo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD}}

            - name: Docker Publish
              run: sudo docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Docker Logout
              run: sudo docker logout https://docker.io
    test_job:
        needs: build_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Run Rabbit MQ
              run: |
                  sudo docker run -itd -p 15672:15672 -p 5672:5672 --network=shadow-net --name rabbitmq rabbitmq:3-management
                  sleep 30s
              
            - name: Run Python Backend
              run: |
                  sudo docker run -itd --link rabbitmq:rabbitmq --network=shadow-net --name market-app ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
                  sleep 30s

            - name: Test Docker Image
              run: |
                  sudo docker exec -i market-app cat /app/test.log

            - name: Clean Docker Deployments
              run: |
                  sudo docker stop market-app && sudo docker rm market-app
                  sudo docker stop rabbitmq && sudo docker rm rabbitmq
    deploy_job:
        needs: test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Deploy Application
              run: |
                  cat README.md
